//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcGCUImagesStarter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int ImageId { get; set; }
        public string ImageTitle { get; set; }
        public string ImageDescription { get; set; }
        public string ImageContributor { get; set; }
        public string ImageURL { get; set; }
        public short ImageWidth { get; set; }
        public short ImageHeight { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
